### ISSUE TITLE
под Лин ничего не делает

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_lint_perl#3]
Perl 5 уже стоит. ошибок не находит ни в чем.
в консоли

cmd
plit_match
None
cmd
plit_match
None

**Comment by ahreenah** [comment]
а если напрямую в консли вызвать его то находит?

**Comment by ahreenah** [comment]
нужен просто perl

**Comment by Alexey-T** [comment]
он и есть просто perl.

user@PC:~$ perl --version

This is perl 5, version 28, subversion 1 (v5.28.1) built for x86_64-linux-gnu-thread-multi
(with 61 registered patches, see perl -V for more detail)

**Comment by Alexey-T** [comment]
работает. если скобки кривы.
